@startuml
class controllers.commands.ingame.ReleaseTheNukeCheatCommand {
- GameSession gameSession
+ void execute()
}


class models.quests.QuestCondition.CollectSunCondition {
+ boolean isSatisfied(QuestCondition)
}

class views.InputHandler {
- {static} Scanner scanner
+ {static} String readLine()
}


class models.entities.plants.bowling.GiantWallnut {
}
class controllers.commands.ingame.AddSunCheatCommand {
- GameSession gameSession
- int count
+ void execute()
}


class models.game.gamemodes.LoveYourPlantsMode {
- int maxPlantsLost
}

class models.entities.zombies.Components.MovementComponent {
- double speed
- double x
- int y
+ void move(StateComponent)
+ double getPositionX()
+ int getPositionY()
}


class models.game.gamemodes.SaveOurSeedsMode {
- List<Plant> protectedPlants
}

class models.entities.plants.classification.Mints {
+ void givePlantFood(List<Plant>)
}

class models.minigames.IZombie {
+ void placeZombie(Zombie,int,int)
+ void start(GameSession)
+ boolean checkWin(GameSession)
}

class models.scoring.FastKillPattern {
}
class models.shop.DailyOffer {
- int id
- LocalDate date
- String plantType
- int basePrice
- int discountPrice
- boolean purchased
}

class controllers.systems.CollectionSystem {
- {static} CollectionSystem instance
+ {static} CollectionSystem getInstance()
+ void purchasePlant(Profile,String)
+ void upgradePlant(Profile,String)
}


class models.entities.plants.classification.Modifier {
+ void applyEffect(Plant,Zombie)
}

class models.entities.plants.classification.WallNuts {
- int armorHp
- boolean blocksJumpers
- boolean isArmor
}

class controllers.systems.ShopSystem {
- {static} ShopSystem instance
+ {static} ShopSystem getInstance()
+ void refreshDailyOffers(Profile)
+ void buyItem(Profile,String,int)
- boolean hasEnoughCurrency(Profile,Currency,int)
- boolean isAtCapacity(Profile,String,int)
- void deductCurrency(Profile,Currency,int)
- void grantItem(Profile,String,int,String)
}


class models.map.Lawnmower {
- boolean used
- int row
+ void Active(Zombie[])
}


class models.entities.collectibles.Sun {
- SunType type
- int amount
- boolean falling
- double targetY
+ void onReachGround()
+ void update()
}


class controllers.commands.profileandsettings.ShowProfileCommand {
- User currentUser
+ void execute()
}


class controllers.commands.ingame.PluckPlantCommand {
- GameSession gameSession
- int tileX
- int tileY
+ void execute()
}


class controllers.commands.collection.UpgradePlantCommand {
- String plantName
- User currentUser
+ void execute()
}


class models.entities.plants.classification.Homing {
- int damage
+ Zombie findTheTarget()
+ void doingTheTask(Zombie)
}


class models.game.gamemodes.ConveyorBeltMode {
}
enum models.game.GameState {
+  PLAYING
+  WON
+  LOST
}

class utils.registry.QuestRegistry {
- {static} QuestRegistry instance
- Map<String,QuestTemplate> questTemplatesByName
+ {static} QuestRegistry getInstance()
+ Map<String,QuestTemplate> getAllQuestTemplates()
+ QuestTemplate getQuestTemplateByName(String)
+ void register(QuestTemplate)
}


class models.minigames.Upgrade {
- Plant basePlant
- Plant lastPlant
- int cost
}

class utils.gameinitializers.GameInitializer {
+ void loadAllData()
}

class models.quests.QuestCondition.TimeLimitCondition {
+ boolean isSatisfied(QuestCondition)
}

class utils.validation.UsernameValidator {
+ boolean validate(String)
}

class models.minigames.WallnutBowling {
+ void placeNut(Row,BowlingType)
+ void start(GameSession)
+ boolean checkWin(GameSession)
}

interface controllers.commands.Command {
~ void execute()
}

class models.entities.intractables.PlantVase {
}
class models.entities.plants.FoodStrategies.BurstShootStrategy {
- ProjectileType projectileType
- int projectileCount
- ShootPattern pattern
+ void executeEffect(Plant)
}


enum models.entities.collectibles.SunType {
+  SPECIAL
+  NORMAL
+  RADIOACTIVE
}

class controllers.commands.ingame.ShowSunCommand {
- GameSession gameSession
+ void execute()
}


class models.entities.zombies.Zombie {
- HealthComponent health
- MovementComponent movement
- StateComponent state
- List<ZombieAbility> abilities
- int wavePointCost
- boolean glowing
+ void addAbility(ZombieAbility)
+ void update()
+ StateComponent getState()
+ MovementComponent getMovement()
+ void setWavePointCost(int)
+ int getWavePointCost()
+ void setGlowing(boolean)
+ boolean isGlowing()
+ List<ZombieAbility> getAbilities()
+ HealthComponent getHealth()
}


class models.game.gamemodes.StandardMode {
+ void onStart(GameSession)
+ void onTick(GameSession)
+ boolean checkWin(GameSession)
+ boolean checkLose(GameSession)
+ boolean requiresSeedSelection(GameSession)
+ boolean isCommandAllowed(String)
}

class views.renderers.MapRenderer {
+ void renderAllTheMap(GameSession)
+ void renderAllZombies(List<Zombie>)
+ void renderAllPlants(List<Cell>)
+ void renderGameSession(GameSession)
}

class models.entities.plants.FoodStrategies.InstantSunProductionStrategy {
- int sunAmount
+ void executeEffect(Plant)
}


abstract class models.entities.Entity {
# String name
# int id
# double x
# int y
# int hp
# boolean isAlive
+ String getName()
+ int getId()
+ void setId(int)
+ int getX()
+ void setX(int)
+ int getY()
+ void setY(int)
+ int getHp()
+ void setHp(int)
+ boolean isAlive()
+ void setAlive(boolean)
+ {abstract}void update()
}


class models.quests.Reward.InventoryReward {
}
class models.entities.zombies.Abilities.TurnIntoKnightAbility {
+ void execute(Zombie)
}

class controllers.commands.authentication.ForgetPasswordCommand {
- String Username
- String email
- SessionManager sessionManager
+ void execute()
}


class utils.Constants {
+ {static} String PASSWORD_HASH_ALGORITHM
}

class models.shop.ShopItem {
- int id
- String name
- int price
- Currency currency
- int capacity
}

class models.game.Level {
- Wave[] waves
- LevelTemplate template
- boolean unlocked
- boolean completed
}

class models.game.gamemodes.PlantWhatYouGet {
- int initialSun
}

class controllers.systems.TimeSystem {
+ void advance(GameSession,int)
- long getElapsedTime(GameSession)
}

class controllers.commands.seedselection.ShowSeedsCommand {
- GameSession gameSession
- boolean showAllSeeds
+ void execute()
}


class factories.QuestFactory {
+ {static} Quest createQuest(String)
}

abstract class models.quests.Reward.Reward {
+ void grant(Profile)
}

class models.entities.zombies.Components.HealthLayer {
- int currentHp
- int maxHp
- ArmorType type
+ int takeDamage(int)
+ int getCurrentHp()
+ ArmorType getType()
}


class models.entities.intractables.GargantuarVase {
}
enum models.map.Terrains.SlipDirection {
+  UP
+  DOWN
}

class models.entities.projectiles.Projectile {
- ProjectileType type
- int damage
- double x
- double y
- int speed
+ void move()
+ void onHit(Zombie)
+ void update()
}


class models.game.GameSession {
- Profile player
- GameMode mode
- Level level
- GameMap map
- int sunAmount
- List<Sun> activeSuns
- List<SeedPacket> selectedSeeds
- int plantFoodCount
- long timeTicks
- int currentWave
- GameState state
- int zombiesKilled
- int plantsLost
+ void plant(int,int,String)
+ void pluck(int,int)
+ void advanceTime(int)
+ void collectSun(int,int)
+ void plantFood(int,int)
+ void onWin()
+ void onLose()
}


class controllers.commands.greenhouse.ShowGreenhouseCommand {
- GreenHouse greenHouse
+ void execute()
}


class utils.registry.LevelRegistry {
- {static} LevelRegistry instance
- Map<String,LevelTemplate> levelTemplatesById
+ {static} LevelRegistry getInstance()
+ LevelTemplate getLevelTemplateById(String)
+ void register(LevelTemplate)
}


class controllers.commands.seedselection.BoostSeedCommand {
- String seedName
- GameSession gameSession
+ void execute()
}


class models.greenhouse.Pot {
- int x
- int y
- PotState state
- String growing
- long readyAtTick
- int speed
- Plant onPot
+ void unlock()
}


enum controllers.commands.profileandsettings.EditAction {
+  USERNAME
+  NICKNAME
+  EMAIL
+  PASSWORD
}

class models.minigames.Beghouled {
- int targetMatches
+ void swap(Cell,Cell)
+ void upgrade(Upgrade)
+ int resolveMatches()
}


class models.entities.zombies.Components.StateComponent {
- boolean isFlying
- boolean isSubmerged
- boolean isFrozen
- boolean isStopped
+ void freeze()
+ void submerge()
+ void fly()
+ boolean isFlying()
+ boolean isSubmerged()
+ boolean isFrozen()
+ boolean isStopped()
}


class utils.gameinitializers.parsers.PlantCSVParser {
+ List<PlantTemplate> parse(String)
}

class controllers.commands.authentication.LoginCommand {
- String username
- String password
- boolean stayLoggedIn
- SessionManager sessionManager
+ void execute()
}


class models.entities.zombies.ZombotanyZombies.PeaShooterZombie {
}
class views.renderers.MenuRenderer.PlantMenuRenderer {
+ void renderAllPlants(PlantRegistry)
+ void renderAvailablePlants(Profile)
+ void addPlant(String)
+ void removePlant(String)
+ void boostPlant()
+ void startGame()
}

class models.quests.DailyQuest {
}
class models.entities.zombies.Abilities.ThrowImp {
+ void execute(Zombie)
}

class models.entities.plants.classification.Lobbers {
- int damage
+ ProjectileType lob(Cell)
}


class controllers.commands.greenhouse.PlantPotCommand {
- GreenHouse greenHouse
- int potX
- int potY
+ void execute()
}


class controllers.commands.ingame.PlantSeedCommand {
- GameSession gameSession
- String plantType
- int tileX
- int tileY
+ void execute()
}


class models.templates.ZombieTemplate {
- int id
- String category
- int baseHp
- int armorHp
- String alias
- int eatDamage
- int eatSpeed
- double speed
- int wavePointCost
- boolean canSpawnPlantFood
- String behavior
- List<String> specialAbilities
}

class models.templates.PlantTemplate {
- int id
- String name
- String category
- List<String> tags
- int cost
- int baseHp
- int attackDamage
- int fireRate
- int sunProductionRate
- String baseAbility
- String plantFoodEffect
- String[] upgrades
- int actionInterval
- int recharge
}

enum models.entities.collectibles.Collectibles {
+  GEM
+  COIN
+  POT
}

class factories.LevelFactory {
+ {static} Level createLevel(String)
}

class models.quests.QuestCondition.NoLossCondition {
+ boolean isSatisfied(QuestCondition)
}

class models.quests.Reward.CurrencyReward {
}
enum models.quests.QuestPriority {
+  CRITICAL
+  HIGH
+  MEDIUM
+  LOW
}

class models.map.Cell {
- int x
- int y
- Plant plant
- Terrain terrain
+ boolean isPlantable
+ void addPlant(Plant)
+ void removePlant()
}


class models.entities.plants.bowling.BowlingType {
+ void update()
}

class controllers.commands.ingame.ShowMapStatusCommand {
- ShowMapStatusAction action
- GameSession gameSession
- int tileX
- int tileY
+ void execute()
}


class controllers.systems.NewsSystem {
- {static} NewsSystem instance
+ {static} NewsSystem getInstance()
+ void addNews(Profile,News)
+ void readNews(Profile,News)
}


class models.quests.QuestCondition.WinWithNoPlantCondition {
+ boolean isSatisfied(QuestCondition)
}

class models.map.Terrains.LowSandTerrain {
- boolean flooded
}

class views.renderers.MenuRenderer.SignUpMenuRenderer {
+ void successOfRegistration(boolean)
+ void pickSecurityQuestions()
}

interface utils.gameinitializers.parsers.Parser {
~ List<T> parse(String)
}

class models.entities.zombies.Abilities.SummonGraveAbility {
+ void execute(Zombie)
}

enum models.game.EnvironmentType {
+  ANCIENT_EGYPT
+  FROSTBITE_CAVES
+  BIG_WAVE_BEACH
+  DARK_AGES
- boolean hasSkySunDrops
- boolean hasWaterTerrain
+ boolean hasSkySunDrops()
+ boolean hasWaterTerrain()
}


class models.map.Terrains.GrassTerrain {
}
enum models.entities.projectiles.ProjectileType {
+  NORMAL_PEA
+  ICE_PEA
+  FIRE_PEA
+  POISON_PEA
+  HEAVY_CHARGED
+  ONION_SMALL
+  ONION_MEDIUM
+  ONION_GIANT
+  MAGIC_BOLT
+  LIGHTNING
+  THORN
+  STAR
+  SPORE
+  FUME
+  CABBAGE
+  CORN_KERNEL
+  BUTTER
+  MELON
+  WINTER_MELON
+  PEPPER
}

class controllers.commands.seedselection.ToggleSeedCommand {
- ToggleAction action
- GameSession gameSession
+ void execute()
}


class models.entities.zombies.Abilities.FishThePlants {
+ void execute(Zombie)
}

class views.renderers.MenuRenderer.GameMenuRenderer {
+ void enterChapter(String)
+ void enterOtherMenusFromThisMenu(String)
+ void coinsAndGemsRenderer(Profile)
+ void cheatRenderForAddingCoinsAndGems()
}

class views.renderers.MenuRenderer.SettingMenuRenderer {
+ void settingRender(int)
}

class views.renderers.LeaderboardRenderer {
+ void listAllPlayersIncreasing(LeaderboardEntry[])
+ void listAllPlayersDecreasing(LeaderboardEntry[])
}

class models.minigames.Zombotany {
~ Zombie zombie
+ void start(GameSession)
+ boolean checkWin(GameSession)
}


enum controllers.commands.collection.ShowListType {
+  ALL_ZOMBIES
+  ALL_PLANTS
+  ZOMBIES
+  PLANTS
}

class models.entities.zombies.ZombotanyZombies.JalapenoZmobie {
}
class models.quests.Reward.UnlockableReward {
}
class controllers.commands.collection.ShowCollectionListCommand {
- User currentUser
- ShowListType type
- ZombieRegistry zombieRegistry
- PlantRegistry plantRegistry
+ void execute()
}


class controllers.systems.SunSystem {
+ double dropRate(long)
+ void SpawnSkySun(GameSession)
+ void SpawnPlantSun(GameSession,double,int,int)
+ void collectSun(GameSession,double,int)
}

enum models.shop.Currency {
+  COIN
+  GEM
}

class controllers.commands.menu.ExitMenuCommand {
- String action
+ void execute()
}


class controllers.commands.profileandsettings.ProfileCommands {
- Profile profile
- EditAction action
- String newValue
- String oldPassword
+ void execute()
}


class models.entities.zombies.Abilities.PushIceAbility {
+ void execute(Zombie)
}

class models.entities.plants.classification.StrikeThrough {
- int damage
- ProjectileType projectileType
+ ProjectileType shoot()
}


class controllers.systems.QuestSystem {
- {static} QuestSystem instance
- QuestContext currentLevelContext
+ {static} QuestSystem getInstance()
+ void startTrackingLevel(GameSession)
+ void recordSunCollected(int)
+ void recordZombieKilled(Zombie,Plant)
+ void recordPlantLost()
+ void evaluateActiveQuests(Profile,GameSession)
+ List<Quest> getSortedQuestsForLog(Profile)
+ void grant(Reward)
}


class views.renderers.MenuRenderer.ProfileMenuRenderer {
- Profile currentProfile
+ void changeUsername()
+ void changeNickname()
+ void changePassword()
+ void changeEmail()
+ void showInfo()
}


class models.game.gamemodes.TimedWar {
- int type
- int timer
- int targetCount
}

class utils.gameinitializers.parsers.ZombieJSONParser {
+ List<ZombieTemplate> parse(String)
}

class models.game.gamemodes.LockedPlantsMode {
- int type
}

interface models.scoring.ScorePattern {
+ int score(KillEvent)
}

class models.entities.zombies.Abilities.StealSunAbility {
- int numberOfSuns
+ void execute(Zombie)
}


class models.templates.QuestTemplate {
- String name
- String description
- String category
- String condition
- String rewardType
- int rewardAmount
- String priority
- List<String> variables
}

class views.renderers.ShopRenderer {
+ void listAllProducts()
+ void listDailyProducts()
+ void successOfBuyingAProduct(String)
}

class utils.validation.PasswordValidator {
+ boolean validate(String)
}

class views.renderers.MenuRenderer.AllMenuRenderer {
- InputRouter inputRouter
+ void showCurrentMenu()
+ void enterMenu()
+ void menuExit()
}


interface utils.regex.Regex {
~ String getPattern()
~ Matcher getMatcher(String)
~ boolean matches(String)
~ String getGroup(String,String)
}

class controllers.engine.InputRouter {
- MenuType currentMenu
+ void startLoop()
+ void routeAndExecute(String)
+ void setCurrentMenu(MenuType)
}


class models.entities.zombies.Components.HealthComponent {
- Stack<HealthLayer> layers
+ boolean isDead()
+ void addLayer(HealthLayer)
+ void applyDamage(int,Plant)
+ boolean tryRemoveMetallicArmor()
- void applyChillEffectToAttacker(Plant)
- void die()
}


class utils.registry.ZombieRegistry {
- {static} ZombieRegistry instance
- Map<String,ZombieTemplate> zombieTemplatesByAlias
+ {static} ZombieRegistry getInstance()
+ Map<String,ZombieTemplate> getZombieTemplatesByAlias()
+ ZombieTemplate getZombieTemplateByAlias(String)
+ void register(ZombieTemplate)
}


class models.quests.MainQuest {
}
class models.quests.QuestContext {
- int totalSunCollected
- int plantsLost
- int totalZombiesKilled
- Map<String,Integer> killsByPlantType
- Cell[][] finalMapGrid
- long levelDurationTicks
+ void addSun(int)
+ void incrementPlantsLost()
+ void recordKill(String)
+ void setFinalMapState(Cell[][])
+ void updateLevelDuration(long)
}


class models.entities.plants.FoodStrategies.InstantGrowing {
+ void executeEffect(Plant)
}

class views.renderers.TravelLogRenderer {
+ void showPage(int)
+ void isPageNumberValid()
}

class utils.validation.NicknameValidator {
+ boolean validate(String)
}

class models.shop.Shop {
- List<ShopItem> permanentItems
- DailyOffer dailyOffer
+ void buy(int,int,String)
}


class models.entities.zombies.Abilities.RepelShoots {
+ void execute(Zombie)
}

class views.OutputHandler {
+ {static} void showMessage(String)
+ {static} void showError(String)
+ {static} void showSuccess(String)
}

class models.game.Wave {
- int number
- boolean isFinal
- int WaveCost
- List<Zombie> zombies
- int totalInitialHp
- int delay
+ void spawn()
+ void isDefeated()
+ double difficultyFactor()
}


class models.entities.zombies.Abilities.KillPlantsAbility {
- boolean isExplorer
- boolean isTorchLight
+ void setExplorer(boolean)
+ void setTorchLight(boolean)
+ boolean isExplorer()
+ boolean isTorchLight()
+ void execute(Zombie)
}


class models.map.Terrains.GraveTerrain {
- int hp
+ void getShot(int)
}


class models.entities.zombies.ZombotanyZombies.WallnutZombie {
}
enum models.leaderboard.LbColumn {
+  LEVEL
+  MINIGAMES
+  DAILY_QUESTS
+  NONDAILY_QUESTS
+  MYOPOINT
}

class utils.gameinitializers.LevelInitializer {
+ {static} void loadAllLevels()
}

class models.entities.zombies.Abilities.RoleTheBarrel {
+ void execute(Zombie)
}

class models.leaderboard.LeaderboardEntry {
- String username
- int lastChapter
- int lastLevel
- int minigamesCompleted
- int dailyQuests
- int nonDailyQuests
- int bestMyoPoint
}

class views.renderers.GreenhouseRenderer {
+ void showGreenhouse(Pot[])
}

class controllers.commands.shopandeconomy.CheatCommand {
- int count
- Currency currency
- boolean isPlantFood
+ void execute()
}


class models.map.Row {
- List<Cell> cells
- int index
- boolean hasZombie
- List<Zombie> activeZombies
- List<Projectile> activeProjectiles
- Lawnmower lawnmower
+ Cell cellAt(int)
+ void setLawnmower()
+ Plant frontPlant()
}


abstract class models.minigames.Minigame {
- int level
- int difficulty
+ {abstract}void start(GameSession)
+ {abstract}boolean checkWin(GameSession)
}


class models.map.Terrains.WaterTerrain {
- int level
}

interface utils.validation.Validator {
+ boolean validate(String)
}

class views.exceptions.GameException {
}
class models.map.Terrains.FrozenTerrain {
- int hp
- Entity inner
+ void melt(int)
}


class controllers.commands.ingame.CollectSunCommand {
- GameSession gameSession
- int x
- int y
+ void execute()
}


class controllers.auth.SessionManager {
- User currentUser
+ void register()
+ boolean login(String,String,boolean)
+ Map<Integer,String> forgetPassword(String,String)
+ boolean answerSecurityQuestions(Map<Integer,String>)
+ void logout()
+ void resetPassword(String)
}


class controllers.systems.GreenhouseSystem {
- {static} GreenhouseSystem instance
+ {static} GreenhouseSystem getInstance()
+ void plantPot(int,int,Profile)
+ void collectPot(int,int,Profile)
+ void updateGrow(int,int,Profile)
+ void unlockPot(int,int,Profile)
+ void speedUpGrowth(Profile,int,int)
- String getRandomPlant(Profile)
}


class models.entities.plants.FoodStrategies.CompositePlantFoodStrategy {
- List<PlantFoodStrategy> strategies
+ void addStrategy(PlantFoodStrategy)
+ void executeEffect(Plant)
}


class models.quests.QuestCondition.SymmetryCondition {
+ boolean isSatisfied(QuestCondition)
}

class views.renderers.MenuRenderer.NewsMenuRenderer {
+ void unreadNewsRender()
+ void allNewsRender()
}

class models.game.gamemodes.DeadLineMode {
- int deadLineColumn
}

class factories.ZombieFactory {
+ {static} Zombie createZombie(String,int,int)
}

enum models.user.Gender {
+  MALE
+  FEMALE
}

class controllers.commands.menu.EnterMenuCommand {
- String menuName
- String chapterName
+ void execute()
}


class models.entities.plants.classification.MeleeAttackers {
- int damage
+ void meleeHit(Zombie)
}


interface models.quests.QuestCondition.QuestCondition {
+ boolean isSatisfied(QuestCondition)
}

class controllers.commands.collection.ShowEntityDetailsCommand {
- User currentUser
- ZombieRegistry zombieRegistry
- PlantRegistry plantRegistry
- String entityName
+ void execute()
}


enum controllers.commands.seedselection.ToggleAction {
+  ADD
+  REMOVE
}

class views.renderers.MenuRenderer.MainMenuRenderer {
+ void logOutRender(boolean)
}

class models.user.Profile {
- int gameNumbers
- int coins
- int gems
- int plantFoodCount
- int difficultyLevel
- int bestNumberOfMeowPoints
- List<News> newsList
- List<Plant> unlockedPlants
- List<Plant> lockedPlants
- List<Zombie> seenZombies
- Map<String,Integer> ownedSeedPackets
- GreenHouse myGreenHouse
- List<Quest> activeQuests
- List<Quest> completedQuests
- int lastChapter
- int lastLevel
- Map<String,Integer> passedMiniGames
- int dailyQuestsDone
- int noneDailyQuestsDone
- boolean hasBoughtDailyOfferToday
+ void addCoins(int)
+ void spendCoins(int)
+ void addGems(int)
+ void spendGems(int)
+ void increaseGameNumbers()
+ int getGameNumbers()
+ int getCoins()
+ int getGems()
+ int getBestNumberOfMeowPoints()
+ List<Plant> getUnlockedPlants()
+ List<Zombie> getSeenZombies()
+ Map<String,Integer> getOwnedSeedPackets()
+ GreenHouse getMyGreenHouse()
+ List<Quest> getActiveQuests()
+ List<Quest> getCompletedQuests()
+ int getLastChapter()
+ int getLastLevel()
+ Map<String,Integer> getPassedMiniGames()
+ int getDailyQuestsDone()
+ int getNoneDailyQuestsDone()
+ void setDifficultyLevel(int)
+ int getDifficultyLevel()
+ void addNews(News)
}


class models.templates.LevelTemplate {
- String id
- String chapter
- int levelNumber
- String mode
- String name
- int startingSun
- List<String> availablePlants
- int firstWaveBudget
- int waveCount
- char[][] terrainLayout
}

class models.entities.zombies.Abilities.EatPlant {
- int speedOfEating
+ void execute(Zombie)
}


class controllers.systems.LeaderboardSystem {
- {static} LeaderboardSystem instance
+ {static} LeaderboardSystem getInstance()
+ List<LeaderboardEntry> sortBy(LbColumn,boolean,DatabaseManager)
- int compareEntries(LeaderboardEntry,LeaderboardEntry,LbColumn)
}


abstract class models.entities.collectibles.Collectible {
# long expireTime
+ void collect()
}


class controllers.systems.CombatSystem {
+ void resolve(GameSession)
- void zombieAttack(GameSession)
- void PlantAttack(GameSession)
- void resolveProjectiles(GameSession)
- void checkLawnmowers(GameSession)
- void processDeaths(GameSession)
- void updateZombieStates(GameSession)
}

class utils.gameinitializers.parsers.QuestCSVParser {
+ List<QuestTemplate> parse(String)
}

class models.entities.zombies.Abilities.ChangeRow {
+ void execute(Zombie)
}

abstract class models.map.Terrains.Terrain {
# boolean plantable
+ {abstract}boolean isPlantable()
+ {abstract}void onZombieEnter(Zombie)
+ {abstract}char symbol()
}


class models.minigames.VaseBreaker {
+ void breakVase(Vase,int,int)
+ void start(GameSession)
+ boolean checkWin(GameSession)
}

class models.entities.zombies.ZombotanyZombies.SquashZombie {
}
class models.map.Terrains.SlipTerrain {
- SlipDirection direction
}

class models.greenhouse.GreenHouse {
- Pot[] pots
- int rows
- int cols
+ void increaseSpeed(int,int)
+ String showStatus()
+ Plant plantPlot(int,int)
+ Plant harvest(int,int)
+ void harvestReward(Plant)
}


enum controllers.commands.ingame.ShowMapStatusAction {
+  SHOW_MAP
+  SHOW_PLANTS_STATUS
+  SHOW_TILE_STATUS
}

enum models.greenhouse.PotState {
+  LOCKED
+  EMPTY
+  READY
+  GROWING
}

class models.entities.plants.classification.Shooters {
- int damage
- int shotsPerAction
- ProjectileType projectileType
+ ProjectileType shoot()
}


class controllers.commands.authentication.RegisterCommand {
- String username
- String password
- String passwordConfirm
- String nickname
- String email
- String gender
- SessionManager sessionManager
+ void execute()
}


class controllers.commands.shopandeconomy.ShowWalletCommand {
- Currency currency
- User currentUser
+ void execute()
}


class models.entities.intractables.Vase {
~ VaseContent content
+ Object breaks()
}


class utils.registry.PlantRegistry {
- {static} PlantRegistry instance
- Map<String,PlantTemplate> plantTemplatesByName
+ {static} PlantRegistry getInstance()
+ PlantTemplate getTemplateByName(String)
+ Map<String,PlantTemplate> getAllPlantTemplates()
+ void register(PlantTemplate)
}


abstract class models.quests.Quest {
- String name
~ QuestPriority priority
~ Reward reward
~ QuestCondition condition
+ {abstract}boolean isComplete(QuestContext)
}


interface models.game.gamemodes.GameMode {
~ void onStart(GameSession)
~ void onTick(GameSession)
~ boolean checkWin(GameSession)
~ boolean checkLose(GameSession)
~ boolean requiresSeedSelection(GameSession)
~ boolean isCommandAllowed(String)
}

class models.entities.zombies.Abilities.ShootingAbility {
+ void execute(Zombie)
}

class controllers.commands.profileandsettings.ChangeDifficultyCommand {
- User currentUser
- int difficulty
+ void execute()
}


class controllers.commands.collection.UnlockPlantCommand {
- String plantName
- User currentUser
- PlantRegistry plantRegistry
+ void execute()
}


class models.game.SeedPacket {
- String plantType
- int cooldownDuration
- long lastPlantedTick
+ boolean isReady()
+ void updateLastPlantedTick()
}


class views.renderers.MenuRenderer.LogInMenuRenderer {
+ void successOfLoggingIn(boolean)
+ void forgetPasswordRender(boolean,User)
}

class controllers.systems.CampaignSystem {
- {static} CampaignSystem instance
+ {static} CampaignSystem getInstance()
+ void completeLevel(Profile,String,int)
+ void unlockNext(Profile,Level)
+ boolean canEnter(Profile,Level)
}


class controllers.commands.menu.ShowCurrentMenuCommand {
+ void execute()
}

class Main {
~ {static} void main(String[])
}

class models.entities.zombies.Abilities.CarryADynamite {
+ void execute(Zombie)
}

class models.scoring.MultiKillPattern {
}
class controllers.engine.GameEngine {
- GameSession gameSession
- CombatSystem combatSystem
- SunSystem sunSystem
- TimeSystem timeSystem
- WaveSystem waveSystem
- boolean running
+ void startLoop(GameSession)
+ void stopLoop()
- void run()
}


class controllers.commands.ingame.RemoveCooldownCheatCommand {
- GameSession gameSession
+ void execute()
}


interface models.entities.zombies.Abilities.ZombieAbility {
~ void execute(Zombie)
}

class models.game.Chapter {
- String name
- Level[] levels
- boolean unlocked
- int zombiesKilledInThisChapter
- EnvironmentType environment
+ boolean isComplete()
}


class controllers.commands.profileandsettings.ShowNewsCommand {
- User currentUser
- boolean showAll
+ void execute()
}


class models.news.News {
- int id
- String title
- String description
- String author
- String date
- boolean read
+ int getId()
+ String getTitle()
+ String getDescription()
+ String getAuthor()
+ String getDate()
+ boolean isRead()
}


class models.scoring.SimultaneousKillPattern {
}
class models.game.gamemodes.NightOpsMode {
}
class models.map.GameMap {
- List<Row> rows
- {static} int rowCount
- {static} int colCount
- List<Collectible> activeCollectibles
+ Cell getCell(int,int)
+ Row getRow(int)
}


class utils.storage.PasswordHasher {
+ {static} String hash(String)
+ {static} boolean matches(String,String)
}

class models.entities.plants.classification.SunProducers {
- int numberOfSuns
- boolean pendingSun
+ Sun produceSun()
}


class models.entities.zombies.Abilities.TurnIntoCat {
+ void execute(Zombie)
}

enum models.entities.intractables.VaseContent {
+  ZOMBIE
+  SUN
+  PLANT
+  SEED_PACKET
}

enum models.entities.projectiles.ShootPattern {
+  STRAIGHT
+  FRONT_AND_BACK
+  ONE_FRONT_TWO_BACK
+  PARALLEL_3_LINES
+  DIAGONAL_4_WAY
+  STAR_5_WAY
+  FAN
+  ALL_DIRECTIONS
+  BOUNCING
+  RANDOM_TARGETS
+  ALL_ENEMIES
}

class controllers.commands.shopandeconomy.BuyShopItemCommand {
- int itemId
- Shop shop
- int count
- String plantType
+ void execute()
}


class factories.PlantFactory {
+ {static} Plant createPlant(String,int,int,int)
}

class controllers.systems.WaveSystem {
+ void maybeStartWave(GameSession)
+ Wave buildWave(GameSession)
- int calculateBudget(int,int,int)
- List<Zombie> buyZombies(List<String>,int)
}

class models.entities.zombies.Abilities.SpinAbility {
+ void execute(Zombie)
}

enum controllers.engine.MenuType {
+  LOGIN_MENU
+  MAIN_MENU
+  PROFILE_MENU
+  SHOP_MENU
+  COLLECTION_MENU
+  PLAY_MENU
+  IN_GAME
+  GREENHOUSE_MENU
+  NEWS_MENU
+  SIGNUP_MENU
+  PLANTS_MENU
+  SETTINGS_MENU
+  ONLINE_MENU
}

class models.map.Terrains.NecromancyTerrain {
+ Zombie spawnFromGrave()
}

class views.renderers.MenuRenderer.CollectionMenuRenderer {
+ void renderAllPlants(PlantRegistry)
+ void renderUnlockedPlants(Profile)
+ void renderPlantDetails(Profile,PlantRegistry,String)
+ void renderAllZombies(ZombieRegistry)
+ void renderSeenZombies(Profile)
+ void renderZombieDetails(Profile,ZombieRegistry,String)
+ void upgradePlant(Plant)
+ void successOfPurchasePlant()
}

enum models.entities.zombies.Components.ArmorType {
+  BASE_BODY
+  CONE
+  BUCKET
+  BRICK
+  ICE_BLOCK
}

enum models.entities.plants.PlantTags {
+  DAY
+  NIGHT
+  SHROOM
+  WRAMP_UP
+  PEA
+  ICE
+  FIRE
+  STACK
+  CHARGE
+  MAGIC
+  POISON
+  WATER
+  A_O_E
+  TRAP
+  MOVE_ZOMBIES
+  SUN
+  EXPLOSIVE
}

class models.entities.plants.Plant {
# int level
# int cost
# int recharge
# int actionInterval
# int cooldown
# boolean thisPlantHasFood
# List<PlantTags> tags
# CompositePlantFoodStrategy plantFoodStrategy
+ void upgrade()
+ boolean isReadyToPlant()
+ void update()
+ boolean isDead()
}


class utils.storage.DatabaseManager {
- Map<String,User> users
- DatabaseManager databaseManager
+ DatabaseManager getInstance()
+ void saveAll()
+ void loadAll()
+ User findUser(String)
+ void addUser(User)
+ boolean usernameExists()
}


class controllers.commands.seedselection.StartLevelCommand {
- GameSession gameSession
+ void execute()
}


interface models.entities.plants.FoodStrategies.PlantFoodStrategy {
~ void executeEffect(Plant)
}

class models.entities.plants.bowling.BowlingWallnut {
- int direction
+ void roll()
+ void bounce()
}


class models.quests.QuestCondition.Lawnmower {
+ boolean isSatisfied(QuestCondition)
}

class models.entities.plants.bowling.ExplodeONut {
+ void detonate()
}

class models.quests.QuestCondition.KillWIthPlantCondition {
+ boolean isSatisfied(QuestCondition)
}

class models.entities.plants.classification.Explosives {
- int damage
- int blastSize
+ void explosion()
}


class models.user.User {
- String username
- String nickname
- String email
- Gender gender
- String hashPassword
- Map<Integer,String> securityQuestions
- Profile profile
- boolean stayLoggedIn
+ String getUsername()
+ void changeUsername(String)
+ String getPassword()
+ void changePassword(String)
+ Profile getProfile()
+ String getNickname()
+ void changeNickname(String)
+ String getEmail()
+ Gender getGender()
+ String getHashPassword()
+ Map<Integer,String> getSecurityQuestions()
+ void setStayLoggedIn(boolean)
+ boolean isStayLoggedIn()
}


class controllers.commands.ingame.FeedPlantCommand {
- GameSession gameSession
- int tileX
- int tileY
+ void execute()
}


class utils.validation.EmailValidator {
+ boolean validate(String)
}

class models.quests.EpicQuest {
}


controllers.commands.Command <|.. controllers.commands.ingame.ReleaseTheNukeCheatCommand
models.quests.QuestCondition.QuestCondition <|.. models.quests.QuestCondition.CollectSunCondition
models.entities.plants.bowling.BowlingType <|-- models.entities.plants.bowling.GiantWallnut
controllers.commands.Command <|.. controllers.commands.ingame.AddSunCheatCommand
models.game.gamemodes.StandardMode <|-- models.game.gamemodes.LoveYourPlantsMode
models.game.gamemodes.StandardMode <|-- models.game.gamemodes.SaveOurSeedsMode
models.entities.plants.Plant <|-- models.entities.plants.classification.Mints
models.minigames.Minigame <|-- models.minigames.IZombie
models.scoring.ScorePattern <|.. models.scoring.FastKillPattern
models.entities.plants.Plant <|-- models.entities.plants.classification.Modifier
models.entities.plants.Plant <|-- models.entities.plants.classification.WallNuts
models.entities.collectibles.Collectible <|-- models.entities.collectibles.Sun
controllers.commands.Command <|.. controllers.commands.profileandsettings.ShowProfileCommand
controllers.commands.Command <|.. controllers.commands.ingame.PluckPlantCommand
controllers.commands.Command <|.. controllers.commands.collection.UpgradePlantCommand
models.entities.plants.Plant <|-- models.entities.plants.classification.Homing
models.game.gamemodes.StandardMode <|-- models.game.gamemodes.ConveyorBeltMode
models.quests.QuestCondition.QuestCondition <|.. models.quests.QuestCondition.TimeLimitCondition
utils.validation.Validator <|.. utils.validation.UsernameValidator
models.minigames.Minigame <|-- models.minigames.WallnutBowling
models.entities.intractables.Vase <|-- models.entities.intractables.PlantVase
models.entities.plants.FoodStrategies.PlantFoodStrategy <|.. models.entities.plants.FoodStrategies.BurstShootStrategy
controllers.commands.Command <|.. controllers.commands.ingame.ShowSunCommand
models.entities.Entity <|-- models.entities.zombies.Zombie
models.game.gamemodes.GameMode <|.. models.game.gamemodes.StandardMode
models.entities.plants.FoodStrategies.PlantFoodStrategy <|.. models.entities.plants.FoodStrategies.InstantSunProductionStrategy
models.quests.Reward.Reward <|-- models.quests.Reward.InventoryReward
models.entities.zombies.Abilities.ZombieAbility <|.. models.entities.zombies.Abilities.TurnIntoKnightAbility
controllers.commands.Command <|.. controllers.commands.authentication.ForgetPasswordCommand
models.game.gamemodes.StandardMode <|-- models.game.gamemodes.PlantWhatYouGet
controllers.commands.Command <|.. controllers.commands.seedselection.ShowSeedsCommand
models.entities.intractables.Vase <|-- models.entities.intractables.GargantuarVase
models.entities.Entity <|-- models.entities.projectiles.Projectile
controllers.commands.Command <|.. controllers.commands.greenhouse.ShowGreenhouseCommand
controllers.commands.Command <|.. controllers.commands.seedselection.BoostSeedCommand
utils.gameinitializers.parsers.Parser <|.. utils.gameinitializers.parsers.PlantCSVParser
controllers.commands.Command <|.. controllers.commands.authentication.LoginCommand
models.entities.zombies.Zombie <|-- models.entities.zombies.ZombotanyZombies.PeaShooterZombie
models.quests.Quest <|-- models.quests.DailyQuest
models.entities.zombies.Abilities.ZombieAbility <|.. models.entities.zombies.Abilities.ThrowImp
models.entities.plants.Plant <|-- models.entities.plants.classification.Lobbers
controllers.commands.Command <|.. controllers.commands.greenhouse.PlantPotCommand
controllers.commands.Command <|.. controllers.commands.ingame.PlantSeedCommand
models.quests.QuestCondition.QuestCondition <|.. models.quests.QuestCondition.NoLossCondition
models.quests.Reward.Reward <|-- models.quests.Reward.CurrencyReward
models.entities.Entity <|-- models.entities.plants.bowling.BowlingType
controllers.commands.Command <|.. controllers.commands.ingame.ShowMapStatusCommand
models.quests.QuestCondition.QuestCondition <|.. models.quests.QuestCondition.WinWithNoPlantCondition
models.map.Terrains.Terrain <|-- models.map.Terrains.LowSandTerrain
models.entities.zombies.Abilities.ZombieAbility <|.. models.entities.zombies.Abilities.SummonGraveAbility
models.map.Terrains.Terrain <|-- models.map.Terrains.GrassTerrain
controllers.commands.Command <|.. controllers.commands.seedselection.ToggleSeedCommand
models.entities.zombies.Abilities.ZombieAbility <|.. models.entities.zombies.Abilities.FishThePlants
models.minigames.Minigame <|-- models.minigames.Zombotany
models.entities.zombies.Zombie <|-- models.entities.zombies.ZombotanyZombies.JalapenoZmobie
models.quests.Reward.Reward <|-- models.quests.Reward.UnlockableReward
controllers.commands.Command <|.. controllers.commands.collection.ShowCollectionListCommand
controllers.commands.Command <|.. controllers.commands.menu.ExitMenuCommand
controllers.commands.Command <|.. controllers.commands.profileandsettings.ProfileCommands
models.entities.zombies.Abilities.ZombieAbility <|.. models.entities.zombies.Abilities.PushIceAbility
models.entities.plants.Plant <|-- models.entities.plants.classification.StrikeThrough
models.game.gamemodes.StandardMode <|-- models.game.gamemodes.TimedWar
utils.gameinitializers.parsers.Parser <|.. utils.gameinitializers.parsers.ZombieJSONParser
models.game.gamemodes.StandardMode <|-- models.game.gamemodes.LockedPlantsMode
models.entities.zombies.Abilities.ZombieAbility <|.. models.entities.zombies.Abilities.StealSunAbility
utils.validation.Validator <|.. utils.validation.PasswordValidator
models.quests.Quest <|-- models.quests.MainQuest
models.entities.plants.FoodStrategies.PlantFoodStrategy <|.. models.entities.plants.FoodStrategies.InstantGrowing
utils.validation.Validator <|.. utils.validation.NicknameValidator
models.entities.zombies.Abilities.ZombieAbility <|.. models.entities.zombies.Abilities.RepelShoots
models.entities.zombies.Abilities.ZombieAbility <|.. models.entities.zombies.Abilities.KillPlantsAbility
models.map.Terrains.Terrain <|-- models.map.Terrains.GraveTerrain
models.entities.zombies.Zombie <|-- models.entities.zombies.ZombotanyZombies.WallnutZombie
models.entities.zombies.Abilities.ZombieAbility <|.. models.entities.zombies.Abilities.RoleTheBarrel
controllers.commands.Command <|.. controllers.commands.shopandeconomy.CheatCommand
models.map.Terrains.Terrain <|-- models.map.Terrains.WaterTerrain
views.exceptions.RuntimeException <|-- views.exceptions.GameException
models.map.Terrains.Terrain <|-- models.map.Terrains.FrozenTerrain
controllers.commands.Command <|.. controllers.commands.ingame.CollectSunCommand
models.entities.plants.FoodStrategies.PlantFoodStrategy <|.. models.entities.plants.FoodStrategies.CompositePlantFoodStrategy
models.quests.QuestCondition.QuestCondition <|.. models.quests.QuestCondition.SymmetryCondition
models.game.gamemodes.StandardMode <|-- models.game.gamemodes.DeadLineMode
controllers.commands.Command <|.. controllers.commands.menu.EnterMenuCommand
models.entities.plants.Plant <|-- models.entities.plants.classification.MeleeAttackers
controllers.commands.Command <|.. controllers.commands.collection.ShowEntityDetailsCommand
models.entities.zombies.Abilities.ZombieAbility <|.. models.entities.zombies.Abilities.EatPlant
models.entities.Entity <|-- models.entities.collectibles.Collectible
utils.gameinitializers.parsers.Parser <|.. utils.gameinitializers.parsers.QuestCSVParser
models.entities.zombies.Abilities.ZombieAbility <|.. models.entities.zombies.Abilities.ChangeRow
models.minigames.Minigame <|-- models.minigames.VaseBreaker
models.entities.zombies.Zombie <|-- models.entities.zombies.ZombotanyZombies.SquashZombie
models.map.Terrains.Terrain <|-- models.map.Terrains.SlipTerrain
models.entities.plants.Plant <|-- models.entities.plants.classification.Shooters
controllers.commands.Command <|.. controllers.commands.authentication.RegisterCommand
controllers.commands.Command <|.. controllers.commands.shopandeconomy.ShowWalletCommand
models.entities.zombies.Abilities.ZombieAbility <|.. models.entities.zombies.Abilities.ShootingAbility
controllers.commands.Command <|.. controllers.commands.profileandsettings.ChangeDifficultyCommand
controllers.commands.Command <|.. controllers.commands.collection.UnlockPlantCommand
controllers.commands.Command <|.. controllers.commands.menu.ShowCurrentMenuCommand
models.entities.zombies.Abilities.ZombieAbility <|.. models.entities.zombies.Abilities.CarryADynamite
models.scoring.ScorePattern <|.. models.scoring.MultiKillPattern
controllers.commands.Command <|.. controllers.commands.ingame.RemoveCooldownCheatCommand
controllers.commands.Command <|.. controllers.commands.profileandsettings.ShowNewsCommand
models.scoring.ScorePattern <|.. models.scoring.SimultaneousKillPattern
models.game.gamemodes.StandardMode <|-- models.game.gamemodes.NightOpsMode
models.entities.plants.Plant <|-- models.entities.plants.classification.SunProducers
models.entities.zombies.Abilities.ZombieAbility <|.. models.entities.zombies.Abilities.TurnIntoCat
controllers.commands.Command <|.. controllers.commands.shopandeconomy.BuyShopItemCommand
models.entities.zombies.Abilities.ZombieAbility <|.. models.entities.zombies.Abilities.SpinAbility
models.map.Terrains.Terrain <|-- models.map.Terrains.NecromancyTerrain
models.entities.Entity <|-- models.entities.plants.Plant
controllers.commands.Command <|.. controllers.commands.seedselection.StartLevelCommand
models.entities.plants.bowling.BowlingType <|-- models.entities.plants.bowling.BowlingWallnut
models.quests.QuestCondition.QuestCondition <|.. models.quests.QuestCondition.Lawnmower
models.entities.plants.bowling.BowlingType <|-- models.entities.plants.bowling.ExplodeONut
models.quests.QuestCondition.QuestCondition <|.. models.quests.QuestCondition.KillWIthPlantCondition
models.entities.plants.Plant <|-- models.entities.plants.classification.Explosives
controllers.commands.Command <|.. controllers.commands.ingame.FeedPlantCommand
utils.validation.Validator <|.. utils.validation.EmailValidator
models.quests.Quest <|-- models.quests.EpicQuest
@enduml